variable "subnet_ids" {}
variable "prefix" {}
variable "vpc_id" {}
variable "path_to_lambda" {}
variable "output_path" {}
variable "function_name" {}
variable "runtime" {}
variable "handler" {}
variable "cognito_client_id" {}
variable "cognito_user_pool_id" {}